### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by kmai31e** [nhulston/ChatCore#15]
Spigot 1.16.4

[23:41:00] [Server thread/ERROR]: Could not load 'plugins\ChatCore-2.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/cranked/chatcore/ChatCore has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:808) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.UnsupportedClassVersionError: me/cranked/chatcore/ChatCore has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_332]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_332]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_332]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[serwer.jar:git-Spigot-37d799b-3eb7236]
        ... 7 more

**Comment by nhulston** [comment]
Hello, your server must be running Java 17 or higher. I recommend updating regardless because a lot of plugins require Java 17 nowadays. Basically you just need to uninstall java on whatever machine your server is running and reinstall it with a newer version of Java

**Comment by kmai31e** [comment]
Mate, you say that the plugin supports versions 1.7-1.19. Versions 1.7-1.16.5 are on Java 8

**Comment by nhulston** [comment]
I'm running Java 17 on Spigot 1.8.8 and the plugin works
https://gyazo.com/253b5e5c2d3eae2f0fbed0a1dea62dd1

**Comment by nhulston** [comment]
Letting you know that the latest version (2.7) is compiled in java 8
