### ISSUE TITLE
ERROR VERSION 2.11

### ISSUE THREAD

**Issue by tomimza** [nhulston/ChatCore#20]
[14:06:07 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatCore v2.11
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.objects.pass.PassType.getName()" because the return value of "io.github.battlepass.loader.PassLoader.passTypeOfId(String)" is null
        at io.github.battlepass.placeholders.PlaceholderApiHook.onRequest(PlaceholderApiHook.java:83) ~[battle-pass-3.13.6.jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.cranked.chatcore.ConfigManager.placeholderize(ConfigManager.java:258) ~[ChatCore-2.11.jar:?]
        at me.cranked.chatcore.events.ChatFormat.onChat(ChatFormat.java:51) ~[ChatCore-2.11.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor248.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-light-"aaf5e39"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2406) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:107) ~[InteractiveChat-4.2.5.1.jar:?]
        at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$2(RedispatchSignedPacket.java:75) ~[InteractiveChat-4.2.5.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nhulston** [comment]
Is this the full error message? There should be something that says 'Caused by...'
But this looks like an error with the Battle Pass <--> PlaceholderAPI. You probably need to contact PlaceholderAPI or Battle Pass devs to fix this
