### ISSUE TITLE
ChatCore doesnt load

### ISSUE THREAD

**Issue by RealMangorage** [nhulston/ChatCore#23]
[12:32:43 INFO]:
[12:32:43 INFO]: [LuckPerms] Loading configuration...
[12:32:43 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[12:32:43 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[12:32:43 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[12:32:45 INFO]: [LuckPerms] Loading messaging service... [SQL]
[12:32:45 INFO]: [LuckPerms] Loading internal permission managers...
[12:32:45 INFO]: [LuckPerms] Performing initial data load...
[12:32:47 INFO]: [LuckPerms] Successfully enabled. (took 4469ms)
[12:32:47 INFO]: [Vault] Enabling Vault v1.7.3-b131
[12:32:47 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[12:32:47 INFO]: [Vault] Enabled Version 1.7.3-b131
[12:32:47 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[12:32:47 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.3
[12:32:47 INFO]: [PlaceholderAPI] Fetching available expansion information...
[12:32:47 INFO]: [ChatCore] Enabling ChatCore v2.13
[12:32:47 ERROR]: Error occurred while enabling ChatCore v2.13 (Is it up to date?)
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at me.cranked.chatcore.ConfigManager.getHelper(ConfigManager.java:308) ~[ChatCore-2.13.jar:?]
        at me.cranked.chatcore.ConfigManager.initMaps(ConfigManager.java:155) ~[ChatCore-2.13.jar:?]
        at me.cranked.chatcore.ChatCore.onEnable(ChatCore.java:55) ~[ChatCore-2.13.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-498]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-498]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.reload(CraftServer.java:1016) ~[paper-1.19.4.jar:git-Paper-498]
        at org.bukkit.Bukkit.reload(Bukkit.java:930) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-498]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2249) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-498]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-498]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-498]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-498]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-498]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-498]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-498]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-498]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:32:47 INFO]: [ChatCore] Disabling ChatCore v2.13
[12:32:47 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[12:32:47 INFO]: 0 placeholder hook(s) registered!
[12:32:47 INFO]: CrazyMangoRage: Reload complete.
[12:32:47 WARN]: Can't keep up! Is the server overloaded? Running 5693ms or 113 ticks behind
[12:32:47 INFO]: Timings Reset
[12:32:47 INFO]: [Vault] Checking for Updates ...
[12:32:47 INFO]: [Vault] No new version available
[12:32:48 INFO]: CrazyMangoRage issued server command: /reload
[12:32:48 INFO]: CrazyMangoRage: Are you sure you wish to reload your server? Doing so may cause bugs and memory leaks. It is recommended to restart instead of using /reload. To confirm, please type /reload confirm
[12:32:48 WARN]: [LuckPerms] Processing login for CrazyMangoRage took 1281ms.
[12:32:50 INFO]: CrazyMangoRage issued server command: /pl

I do have Vault and PlaceholdeAPI

**Comment by nhulston** [comment]
Hello, I believe it's because you're missing a config section. If you updated the plugin recently make sure to add these lines to your config:

`custom-death-messages-enabled: true`
`death-messages-color: '&7'`
`death-messages-player-color: '&c'`

**Comment by RealMangorage** [comment]
Also does your plugin work across servers?

This is the cfg: 

# _____                 _            _  _____
# / ____|               | |          | |/ ____|
# | |     _ __ __ _ _ __ | | _____  __| | |     ___  _ __ ___
# | |    | '__/ _` | '_ \| |/ / _ \/ _` | |    / _ \| '__/ _ \
# | |____| | | (_| | | | |   <  __/ (_| | |___| (_) | | |  __/
# \_____|_|  \__,_|_| |_|_|\_\___|\__,_|\_____\___/|_|  \___|
#
#
#   A plugin created by Cranked
#   Mc-Market: https://www.mc-market.org/resources/13998/
#   Spigot: https://www.spigotmc.org/resources/chat-core-manage-control-format-your-chat-everything-youll-ever-need.97447/

#############################################################
## +------------------------------------------------------+ #
## |                  General Settings                    | #
## +------------------------------------------------------+ #
#############################################################

# Versions 1.16+: You can use color codes. Ex: &#000000Hello!

reload-msg: '&aChatCore has been reloaded.'
no-permission-msg: '&cNo permission.'
# Useful tip: If you want to change the unknown command message, there is no need
# to download a plugin to do this for you. Simply go to spigot.yml, change the
# field 'unknown-command', and use § for color codes instead of &
# Example: unknown-command: §8[§bServer§8] §7Unknown command.

# You can center ANY message in this whole config file by putting {center} in the message.
help-msg:
  - '&8&m                                                                                '
  - ''
  - '{center}&d&lCHAT CORE'
  - ''
  - '&d        MC-Market Page &8>> &fhttps://www.mc-market.org/resources/13998/'
  - ''
  - '&d/chat &f- Bring up this help page'
  - '&d/chat clear &7<-s/-a> &f- Clears the chat'
  - '&d/chat slow &7<time> <-s/-a> &f- Slow the chat'
  - '&d/chat lock &7<-s/-a> &f- Lock the chat'
  - '&d/chat staff <message> &f- Toggle or send a message to staff chat'
  - '&d/chat spy &f- Enable command spy'
  - '&d/chat announce &f- Announce a message to the server'
  - '&d/chat warn &f- Warn a message to the server'
  - '&d/chat staffannounce &f- Announce a message to the online staff'
  - '&d/chat reload &f- Reload configuration files'
  - ''
  - '&8&m                                                                                '


#############################################################
## +------------------------------------------------------+ #
## |                  Clear Chat Settings                 | #
## +------------------------------------------------------+ #
#############################################################

clear-chat-enabled: true
clear-msg: '&aThe chat was cleared by %player%.'
clear-msg-anon: '&aThe chat was cleared.'

#############################################################
## +------------------------------------------------------+ #
## |                  Lock Chat Settings                  | #
## +------------------------------------------------------+ #
#############################################################

lock-chat-enabled: true
lock-msg: '&aThe chat has been locked by %player%.'
lock-msg-anon: '&aThe chat has been locked.'
unlock-msg: '&aThe chat has been unlocked by %player%.'
unlock-msg-anon: '&aThe chat has been unlocked.'
locked-msg: '&cThe chat is currently disabled.'
lock-silent-msg: '&aYou silently locked the chat.'
unlock-silent-msg: '&aYou silently unlocked the chat.'


#############################################################
## +------------------------------------------------------+ #
## |                  Slow Chat Settings                  | #
## +------------------------------------------------------+ #
#############################################################

slow-chat-enabled: true
slow-msg: '&aThe chat was slowed to a %time% second delay by %player%.'
slow-msg-anon: '&aThe chat was slowed to a %time% second delay.'
slow-usage-msg: '&cUsage: /chat slow <time in sec OR 0 to end>'
slow-silent-msg: '&aYou silently slowed the chat to a %time% second delay.'
slow-delay-msg: '&cThe chat is slowed, so you cannot talk for another %time% seconds.'
unslow-msg: '&aThe chat is no longer slowed.'
unslow-silent-msg: '&aYou silently removed the slow delay in chat.'


#############################################################
## +------------------------------------------------------+ #
## |                  Chat Delay Settings                 | #
## +------------------------------------------------------+ #
#############################################################

# Set to 0 to disable
delay-in-millis: 500
delay-msg: '&cYou cannot talk for another %time% seconds.'


#############################################################
## +------------------------------------------------------+ #
## |                Command Delay Settings                | #
## +------------------------------------------------------+ #
#############################################################

# Set to 0 to disable
command-delay-in-millis: 250
command-delay-msg: '&cYou cannot run a command for another %time% seconds.'


#############################################################
## +------------------------------------------------------+ #
## |                 Staff Chat Settings                  | #
## +------------------------------------------------------+ #
#############################################################

# If you want to add a command shortcut such as /sc, then you can use commands.yml,
# which is found in your base server folder (the same folder as the jar)
# Example:
# sc:
#   - chat staff $1-
# I'm not doing this by default because I don't want to overwrite any existing commands
# and I want to give you the freedom to choose what shortcut you want to use.

staff-chat-enabled: true
staff-chat-format: '&8[&b&lSTAFF&8] &c%player%&f: %message%'
staff-chat-on-msg: '&aStaff chat has been enabled.'
staff-chat-off-msg: '&cStaff chat has been disabled.'


#############################################################
## +------------------------------------------------------+ #
## |                  Donator Chat Settings               | #
## +------------------------------------------------------+ #
#############################################################

# If you want to add a command shortcut such as /dc, then you can use commands.yml,
# which is found in your base server folder (the same folder as the jar)
# Example:
# sc:
#   - chat donator $1-

donator-chat-enabled: true
donator-chat-format: '&8[&e&lDONATORS&8] &e%player%&f: %message%'
donator-chat-on-msg: '&aDonator chat has been enabled.'
donator-chat-off-msg: '&cDonator chat has been disabled.'


#############################################################
## +------------------------------------------------------+ #
## |                  Anti Caps Settings                  | #
## +------------------------------------------------------+ #
#############################################################

anti-caps-enabled: true

# What % of the msg should be caps before we edit the message?
anti-caps-percentage: 50

# How many characters must the message be before we edit the message? (so chats like "LOL" wont be affected)
anti-caps-min-length: 10


#############################################################
## +------------------------------------------------------+ #
## |                 Add Period Settings                  | #
## +------------------------------------------------------+ #
#############################################################

add-period-enabled: true
add-period-min-length: 10


#############################################################
## +------------------------------------------------------+ #
## |                Blocked Words Settings                | #
## +------------------------------------------------------+ #
#############################################################

blocked-words-replace-word: '*****'
blocked-words-replace-char: '*'

# to disable, do:   blocked-words: []
blocked-words:
  - 'wtf'                 # Will not run a punishment
  - 'shit, minor'         # Will run commands from punishment 'minor'
  - 'kys, severe'         # Will run commands from punishment 'severe'

# "Ass" will be detected but "compass" will not
# (Don't put the same word in both categories, just choose one)
blocked-words-ignore-in-bigger-words:
  - 'ass, minor'

# Add as many categories and name them whatever you would like
blocked-words-punishments:
  minor:
    - 'mute %player% -s 1m &fSwearing (&c%word%&f)'        # Or use %message% as a placeholder
  severe:
    - 'chat staffannounce &e%player% &fswore (&e%word%&f)'
    - 'mute %player% -s 3m &fSwearing (&c%word%&f)'


#############################################################
## +------------------------------------------------------+ #
## |              Blocked Commands Settings               | #
## +------------------------------------------------------+ #
#############################################################

blocked-commands-msg: '&cThat command is disabled.' #another fun option would be to make this message the same as your unknown command message
blocked-commands-warn-staff: true
blocked-commands-warn-staff-msg: '&c&lWARNING&f: &c%player% &ftried to use the command ''&c%command%&f'''

# In general, this is recommended to avoid players from seeing what plugins you have installed
# If you want to block suggestions with colon, thus preventing them from seeing your plugins,
# set 'send-namespaced' in spigot.yml to false
block-all-commands-containing-colon: true

# Set to '' to disable
block-all-commands-containing-colon-msg: '&cYou cannot use colons in commands.'
# IMPORTANT TIP: if you want to block players from using '/ver ' or '/about ' (which shows all plugins!), negate the permission 'bukkit.command.version'
# This removes the need for external plugins that will only slow down your server!
blocked-commands:      # to disable, do:   blocked-commands: []
  - '//calc, crash'
  - '//calculate, crash'
  - '/?'
  - '/help'
  - '/ehelp'
  - '/about'
  - '/eabout'
  - '/info'
  - '/bukkit:?'
  - '/bukkit:about'
  - '/bukkit:help'
  - '/bukkit:pl'
  - '/bukkit:plugins'
  - '/bukkit:ver'
  - '/bukkit:version'
  - '/icanhasbukkit'
  - '/minecraft:help'
  - '/pl'
  - '/plugin'
  - '/plugins'
  - '/ver'
  - '/version'

blocked-commands-punishments:
  crash:
    - 'kick %player% -s Don''t try to crash our server.'        # Or use %command% as a placeholder


#############################################################
## +------------------------------------------------------+ #
## |                 Command Spy Settings                 | #
## +------------------------------------------------------+ #
#############################################################

command-spy-enabled: true
command-spy-format: '&d%player%&f %command%'
command-spy-on-msg: '&aYou have enabled command spy.'
command-spy-off-msg: '&cYou have disabled command spy.'
command-spy-enabled-on-join: false
command-spy-ignored-commands:     # to disable, do:   command-spy-ignored-commands: []
  - '/example'
  - '/test2'


#############################################################
## +------------------------------------------------------+ #
## |                  Auto Caps Settings                  | #
## +------------------------------------------------------+ #
#############################################################

auto-caps-enabled: true
auto-caps-min-length: 3


#############################################################
## +------------------------------------------------------+ #
## |                   Announce Settings                  | #
## +------------------------------------------------------+ #
#############################################################

announce-enabled: true
announce-format: '&a&lAnnouncement&f: %message%'
announce-usage: '&cUsage: /chat announce <message>'

# set to NONE or something from this list:
# 1.7: https://pastebin.com/9jbmgjHb
# 1.8: https://pastebin.com/chgFQ6Qe
# 1.9: https://pastebin.com/gPVc30AX
# 1.10: https://pastebin.com/rzrMVG2W
# 1.11: https://pastebin.com/1LqmZmec
# 1.12: https://pastebin.com/fpjUVppS
# 1.13: https://pastebin.com/CkQ1WZuw
# 1.14: https://pastebin.com/Z3eh7SP5
# 1.15: https://pastebin.com/BZeQSYMN
# 1.16: https://pastebin.com/KeaGT8Gi
# 1.17: https://pastebin.com/X0US4f7D
# 1.18: https://pastebin.com/VuAUTguK
# 1.19: https://pastebin.com/smFzazEu
announce-sound: 'NONE'

warning-enabled: true
warning-format: '&c&lWarning&f: %message%'
warning-usage: '&cUsage: /chat warn <message>'
warning-sound: 'NONE'
staff-announce-enabled: true
staff-announce-format: '&d&lStaff Announcement&f: %message%'
staff-announce-usage: '&cUsage: /chat staffannounce <message>'
staff-announce-sound: 'NONE'


#############################################################
## +------------------------------------------------------+ #
## |                 Colored Text Settings                | #
## +------------------------------------------------------+ #
#############################################################

# Players with permission 'chatcore.coloredtext' can use & to send colored text in chat
# If using essentials, set to false and use the permissions 'essentials.chat.color' and 'essentials.msg.color' instead
colored-chat-enabled: true


#############################################################
## +------------------------------------------------------+ #
## |             Anti Advertisement Settings              | #
## +------------------------------------------------------+ #
#############################################################

anti-ad-enabled: true
anti-ad-msg: '&cAdvertising is not allowed.'
anti-ad-inform-msg: '&c&lWARNING: &f%player% tried to advertise: %message%'

# Setting 1 will cancel the message, setting 2 will modify the message to remove periods from the link
anti-ad-setting: 1

anti-ad-whitelist:
  - 'minecraft.net'
  - 'mojang.com'


#############################################################
## +------------------------------------------------------+ #
## |                  Join Quit Messages                  | #
## +------------------------------------------------------+ #
#############################################################

custom-join-quit-messages-enabled: true

# Set to '' to disable join and quit messages (custom-join-quit-messages-enabled must be true then)
join-msg: '&8[&a&l+&8] &f%player%'
quit-msg: '&8[&c&l-&8] &f%player%'
vip-join-msg: '&8[&a&l+&8] &b%player%'
vip-quit-msg: '&8[&c&l-&8] &b%player%'


#############################################################
## +------------------------------------------------------+ #
## |                Chat Format Settings                  | #
## +------------------------------------------------------+ #
#############################################################

custom-chat-format-enabled: true

# If name-hover-enabled is true, and you have factions, use the following format instead:
#default-format: '%rel_factionsuuid_relation_color%%factionsuuid_player_role%%factionsuuid_faction_name% %prefix%%name%%suffix% &8>> &f%message%'
default-format: '%prefix%%name%%suffix% &8>> &f%message%'

# Make sure the name of the rank matches your permissions plugin. Vault is required for rank-formats to work.
rank-formats:
  group1: '%prefix%%name%%suffix% &8>> &f%message%'
  group2: '%prefix%%name%%suffix% &8>> &b%message%'

name-hover-enabled: true

# This example uses PlaceholderAPI placeholders. You may need to use /papi ecloud download (expansion name).
# List of placeholders here: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
hover-format:
  - '%prefix%%name%'
  - '&7Balance: &e$%vault_eco_balance_formatted%'
  - '&7Time played: &e%statistic_time_played%'
  - '&7Faction: %rel_factionsuuid_relation_color%%factionsuuid_faction_name%'
  - ''
  - '&eClick to send %name% &ea message!'

# 'none' to disable, 'url', 'command', 'suggestcommand'
click-action-mode: 'suggestcommand'
# 'https://google.com', '/give %name% stone', '/msg %name% '
click-action: '/msg %name% '


#############################################################
## +------------------------------------------------------+ #
## |                   Mention Settings                   | #
## +------------------------------------------------------+ #
#############################################################

# players need permission chatcore.mention to mention other players
mention-enabled: true
mention-color: '&a&l'

# set to NONE or something from this list:
# 1.7: https://pastebin.com/9jbmgjHb
# 1.8: https://pastebin.com/chgFQ6Qe
# 1.9: https://pastebin.com/gPVc30AX
# 1.10: https://pastebin.com/rzrMVG2W
# 1.11: https://pastebin.com/1LqmZmec
# 1.12: https://pastebin.com/fpjUVppS
# 1.13: https://pastebin.com/CkQ1WZuw
# 1.14: https://pastebin.com/Z3eh7SP5
# 1.15: https://pastebin.com/BZeQSYMN
# 1.16: https://pastebin.com/KeaGT8Gi
# 1.17: https://pastebin.com/X0US4f7D
# 1.18: https://pastebin.com/VuAUTguK
# 1.19: https://pastebin.com/smFzazEu
mention-sound: 'NONE'
# Example: mention-sound: 'ENTITY_CHICKEN_EGG'


#############################################################
## +------------------------------------------------------+ #
## |                    MOTD Settings                     | #
## +------------------------------------------------------+ #
#############################################################

motd-enabled: true
motd:
  - ''
  - ''
  - ''
  - '{center}&5★ &d&l&nSERVER NAME&r &5★'
  - ''
  - '&d&l{center}SERVER IP &8» &fplay.serverip.com'
  - '&d&l{center}STORE &8» &fshop.serverip.com'
  - '&d&l{center}DISCORD &8» &fdiscord.serverip.com'
  - ''
  - ''


#############################################################
## +------------------------------------------------------+ #
## |                Auto Broadcast Settings               | #
## +------------------------------------------------------+ #
#############################################################

auto-broadcast-enabled: true
auto-broadcast-delay: 30
# True = random message, false = in order
auto-broadcast-random: true

# Separate lines with %newline%
auto-broadcast-messages:
  - '&8&m                                                                                %newline%%newline%&d&l{center}Announcement%newline%%newline%&e{center}Insiding is a bannable offense!%newline%%newline%&8&m                                                                                '
  - '&eHelp&f: Use &e/auction &fto access the auction house!'
  - '&eHelp&f: Visit our website for updates at &ewebsite.com'


#############################################################
## +------------------------------------------------------+ #
## |              Command/Chat Log Settings               | #
## +------------------------------------------------------+ #
#############################################################

chat-logger-enabled: true
chat-logger-staff-chat-enabled: true
chat-logger-donator-chat-enabled: true
chat-logger-included-commands:
  - '/m'
  - '/em'
  - '/msg'
  - '/emsg'
  - '/whisper'
  - '/ewhisper'
  - '/tell'
  - '/etell'
  - '/t'
  - '/et'
  - '/me'
  - '/eme'
  - '/r'
  - '/er'
  - '/reply'
  - '/ereply'
command-logger-enabled: true
command-logger-ignored-commands:
  - '/help'
logger-format: '[%time%] %player%: %message% '


#############################################################
## +------------------------------------------------------+ #
## |                  Anti-ASCII Settings                 | #
## +------------------------------------------------------+ #
#############################################################

# This disables all characters with an ASCII code >= 128 (pretty much anything not on the standard keyboard)
# This is recommended to stop bypassing swear and anti-advertising filter
disable-ascii: true
ascii-cancel: true          # If true, cancels the message. If false, replaces the ASCII symbol with the replacement character
ascii-cancel-msg: '&cYou cannot use ASCII characters.'
ascii-replace-character: '*'


#############################################################
## +------------------------------------------------------+ #
## |                 Custom Death Messages                | #
## +------------------------------------------------------+ #
#############################################################

custom-death-messages-enabled: true
death-messages-color: '&7'
death-messages-player-color: '&c'

**Comment by nhulston** [comment]
Apologies, it has been fixed in the latest update 2.14
